openapi: "3.0.2"
info:
  title: API Mahasiswa
  description: API untuk mengelola data mahasiswa
  version: '1.0.0'
  termsOfService: http://swagger.io/terms/
  contact:
    name: Admin Mahasiswa
    email: admin@mahasiswa.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://api.mahasiswa.com/v1
    description: Production server
  - url: https://api-staging.mahasiswa.com/v1
    description: Staging server
tags:
  - name: Mahasiswa
    description: Endpoint terkait dengan pengelolaan data mahasiswa
paths:
  /mahasiswa:
    get:
      tags:
        - Mahasiswa
      summary: Mendapatkan daftar mahasiswa
      description: Mengambil semua data mahasiswa yang terdaftar
      operationId: getMahasiswa
      responses:
        '200':
          description: Daftar mahasiswa berhasil diambil
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Mahasiswa'
        '500':
          description: Kesalahan server
    post:
      tags:
        - Mahasiswa  
      summary: Menambah data mahasiswa baru
      description: Menambahkan data mahasiswa baru ke dalam sistem
      operationId: addMahasiswa
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MahasiswaInput'
      responses:
        '201':
          description: Data mahasiswa berhasil ditambahkan
        '400':
          description: Data tidak valid
  /mahasiswa/{id}:
    get:
      tags:
        - Mahasiswa
      summary: Mendapatkan detail mahasiswa
      description: Mendapatkan informasi detail mahasiswa berdasarkan ID
      operationId: getMahasiswaById
      parameters:
        - name: id
          in: path
          required: true
          description: ID mahasiswa
          schema:
            type: string
      responses:
        '200':
          description: Detail mahasiswa berhasil diambil
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mahasiswa'
        '404':
          description: Data mahasiswa tidak ditemukan
        '500':
          description: Kesalahan server
    put:
      tags:
        - Mahasiswa
      summary: Memperbarui data mahasiswa
      description: Memperbarui informasi mahasiswa berdasarkan ID
      operationId: updateMahasiswa
      parameters:
        - name: id
          in: path
          required: true
          description: ID mahasiswa yang akan diperbarui
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MahasiswaInput'
      responses:
        '200':
          description: Data mahasiswa berhasil diperbarui
        '400':
          description: Data tidak valid
        '404':
          description: Data mahasiswa tidak ditemukan
        '500':
          description: Kesalahan server
    delete:
      tags:
        - Mahasiswa
      summary: Menghapus data mahasiswa
      description: Menghapus data mahasiswa berdasarkan ID
      operationId: deleteMahasiswa
      parameters:
        - name: id
          in: path
          required: true
          description: ID mahasiswa yang akan dihapus
          schema:
            type: string
      responses:
        '204':
          description: Data mahasiswa berhasil dihapus
        '404':
          description: Data mahasiswa tidak ditemukan
        '500':
          description: Kesalahan server
components:
  schemas:
    Mahasiswa:
      type: object
      properties:
        id:
          type: string
          description: ID unik mahasiswa
        nama:
          type: string
          description: Nama lengkap mahasiswa
        nim:
          type: string
          description: Nomor Induk Mahasiswa
        jurusan:
          type: string
          description: Jurusan mahasiswa
        angkatan:
          type: integer
          description: Tahun angkatan mahasiswa
    MahasiswaInput:
      type: object
      properties:
        nama:
          type: string
          description: Nama lengkap mahasiswa
        nim:
          type: string
          description: Nomor Induk Mahasiswa
        jurusan:
          type: string
          description: Jurusan mahasiswa
        angkatan:
          type: integer
          description: Tahun angkatan mahasiswa
      required:
        - nama
        - nim
        - jurusan
        - angkatan
